# Judge0 Configuration File
JUDGE0_VERSION=1.13.0
MAX_SUBMISSIONS_PER_REQUEST=100
MAX_CPU_TIME_LIMIT=15.0
MAX_WALL_TIME_LIMIT=30.0
MAX_MEMORY_LIMIT=256000
MAX_STACK_LIMIT=64000
MAX_MAX_PROCESSES_AND_OR_THREADS=60
MAX_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
MAX_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
